import { Providers } from "./provider";
import { Anonymous_Pro, Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header";

const anonymous_Pro = Anonymous_Pro({
  variable: "--font-anonymous-sans",
  weight: "400",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter-sans",
  weight: "700",
  subsets: ["latin"],
});;

export const metadata = {
  title: "Mulbet",
  description: "Generated by create next app",
  icons: {
    icon: "/mulbet.jpeg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${anonymous_Pro.variable}`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
